## Problem 1
A case-control study of esophageal cancer was performed. Daily alcohol consumption was ascertained (H = high, L = low). The data was stratified by 2 age groups.

Low age group:

|  | H | L |
| - | - | - |
|**Case** | 8 | 5 |
|**Control** | 52 | 164 |



High age group:

|  | H | L |
| - | - | - |
|**Case** | 25 | 21 |
|**Control** | 29 | 128 |

Assuming a constant odds ratio across age-strata, test to see if the odds ratio is 1 and report a Pvalue

In [145]:
dat <- array(c(8, 5, 52, 164, 25, 21, 29, 128), dim=c(2, 2, 2))
dat
mantelhaen.test(dat)

, , 1

     [,1] [,2]
[1,]    8   52
[2,]    5  164

, , 2

     [,1] [,2]
[1,]   25   29
[2,]   21  128


	Mantel-Haenszel chi-squared test with continuity correction

data:  dat
Mantel-Haenszel X-squared = 30.354, df = 1, p-value = 3.6e-08
alternative hypothesis: true common odds ratio is not equal to 1
95 percent confidence interval:
 2.842789 9.501945
sample estimates:
common odds ratio 
          5.19731 


In [119]:
# library('pander')

# whickham1 <- matrix(c(443, 139, 502, 230), byrow=TRUE, nrow=2)
# rownames(whickham1) <- c("Smoker", "Non-Smoker")
# colnames(whickham1) <- c("Alive", "Dead")
# pander(addmargins(whickham1))

ERROR: Error in library("pander"): there is no package called ‘pander’


## Problem 2
The Biostatistics and Epidemilogy departments are running a 10K road race. There are three pairs of runners. In each case, a runner from Biostat was matched to a runner from Epi of the same age, gender and degree of running experience. The difference in each pairs times was taken and a signed rank test performed.

What is the smallest value that the two sided exact signed rank p-value could take?

In [167]:
df = data.frame(x=c(-6, -4, -2, 0, 2, 4, 6), p=c(1/8, 1/8, 1/8, 2/8, 1/8, 1/8, 1/8))
cat('sum(df$x):', sum(df$x))
cat('\nsum(df$p):', sum(df$p))
min_pval=sum(df[df$x>=6 | df$x <= -6, ])
cat('\nmin_pval:', min_pval)

sum(df$x): 0
sum(df$p): 1
min_pval: 0.25

## Problem 3
Two computer based methods for diagnostic imaging are being studied. Ten images were processed with both methods, resulting in a + or − diagnosis for each method and image. The data are as follows:

||||Method A |
|-| - | - | - |
||  | + | - |
|**MethodB**|**+** | 55 | 41 |
||**-** | 12 | 20 |

Where Method A is represeted with the two columns and Method B is represented on the rows. What is the P-value for a of the hypothesis that the marginal probability of a positive diagnosis is the same for the two methods? (Use the large sample version.)

In [180]:
pval = pbinom(40, 12+41, .5, lower.tail=F) + pbinom(12, 12+41, .5, lower.tail=T)
cat('Exact pval:', pval)

mcnemar.test(matrix(c(55, 12, 41, 20), 2))

Exact pval: 8.171335e-05


	McNemar's Chi-squared test with continuity correction

data:  matrix(c(55, 12, 41, 20), 2)
McNemar's chi-squared = 14.792, df = 1, p-value = 0.00012


## Problem 4
Two computer based methods for diagnostic imaging are being studied. Ten images were processed with both methods, resulting in a + or − diagnosis for each method and image. The data are as follows:

||||Method A |
|-| - | - | - |
||  | + | - |
|**MethodB**|**+** | 55 | 41 |
||**-** | 12 | 20 |

Where Method A is represeted with the two columns and Method B is represented on the rows.  What is the marginal odds ratio of a positive diagnosis comparing the two methods? (Put the odds associated with Method B in the numerator.)

In [198]:
# n11=794
# n12=150
# n21=86
# n22=570

n11=55
n12=41
n21=12
n22=20

n = n11 + n12 + n21 + n22

pi1p= (n11+n12)/n
pi2p= (n21+n22)/n
pip1= (n11+n21)/n
pip2= (n12+n22)/n

pi11 = n11/n
pi12=n12/n
pi21=n21/n
pi22=n22/n

or_b_2_a = pi1p/pi2p/(pip1/pip2)
cat('or_b_2_a:', or_b_2_a)

theta_hat=log(pi1p*pip2/(pip1*pi2p))
cat('\ntheta_hat:', theta_hat)

se_hat = sqrt( ( (pi1p*pi2p)^-1 + (pip1*pip2)^-1 - 2*( pi11*pi22 - pi12*pi21 )/( pi1p*pi2p*pip1*pip2) ) / n )
cat('\nse_hat:', se_hat)

ci = theta_hat + c(-1, 1) * 1.96 * se_hat
cat('\nci:', exp(ci))

or_b_2_a: 2.731343
theta_hat: 1.004794
se_hat: 0.2461472
ci: 1.685977 4.424875

## Problem 5
A matched case control study was executed to study an airborn environmental toxicant's effect on lung cancer. The data are:

![](https://d3c33hcgiwev3.cloudfront.net/imageAssetProxy.v1/cAilR2bVEeWsnwqg7P8S6Q_95d8652f38c1f53df78937ca5b9ec5e4_q5-table.png?expiry=1685491200000&hmac=JffKaFpO_BqBSudrGfFmRaGqo_FnqjOcmTHfrlJhviM)

What is the conditional odds ratio of odds of exposure for cases over odds of exposure for controls?

In [199]:
dat = c(243, 189, 54, 153)
n11 = 243
n12 = 54
n21=189
n22=153

oodsExpo4C=n11/n21
oddsExpo4Ctrl=n12/n22

or_oodsExpo4C_oddsExpo4Ctrl = oodsExpo4C/oddsExpo4Ctrl
or_oodsExpo4C_oddsExpo4Ctrl

[1] 3.642857

## Problem 5
A topical rash treatment was applied to a portion of a rash on n patients. A quantitative measure of redness was calculated for the treated and untreated regions of the rash. A sign of + was given when the treated area was less red  (more improved) than the untreated area and a − sign when it was not. It is desired to know whether the treatment improves the rash. 

How many possible values can the P-value for the sign test take?

## Other Miscs

In [168]:
c(-1, 1)*1.96*sqrt(1/432+1/297+1/207+1/342) + log(2.4)

[1] 0.6482717 1.1026657

In [98]:
2*pnorm(-log(2.4)/sqrt(1/432+1/297+1/207+1/342), lower.tail=T)

[1] 7.552559

## Problem 1
At a party a friend brags that they can tell the difference between cheap and expensive wine. You ask him to taste eight glasses wine for which you have randomized as 4 expensive and 4 cheap. Calculate a P-vlaue for the relevant exact hypothesis test using R's fisher.test function.

In [46]:
x = c(4, 2)
y=c(1,6)
fisher.test(matrix(c(4, 2, 1, 6), ncol=2))


	Fisher's Exact Test for Count Data

data:  matrix(c(4, 2, 1, 6), ncol = 2)
p-value = 0.1026
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
   0.5364938 682.2665965
sample estimates:
odds ratio 
  9.470989 


## Problem 2
A drug treatment (T = treatment, P = Placebo) has been randomized to 5 patients in each arm. Consider testing an increase in side effects (S = side effects, N = none). The data are:

x=c(3, 1)

y = c(2, 4)

In [60]:
fisher.test(matrix(c(3, 1, 2, 4), ncol=2), alternative='greater')
fisher.test(matrix(c(3, 1,2, 4), ncol=2), alternative='less')


	Fisher's Exact Test for Count Data

data:  matrix(c(3, 1, 2, 4), ncol = 2)
p-value = 0.2619
alternative hypothesis: true odds ratio is greater than 1
95 percent confidence interval:
 0.3152217       Inf
sample estimates:
odds ratio 
  4.918388 



	Fisher's Exact Test for Count Data

data:  matrix(c(3, 1, 2, 4), ncol = 2)
p-value = 0.9762
alternative hypothesis: true odds ratio is less than 1
95 percent confidence interval:
   0.0000 191.9862
sample estimates:
odds ratio 
  4.918388 


## Problem 5
100 people who took a pain medication for chronic pain were asked if they still had pain one hour after receiving the dose. They received the dose on two separate weeks. The results are given below with the result of the first week's  dose on the rows and the second week's on the columns.
(43, 4, 8, 45)

In [58]:
chisq.test(matrix(c(43, 4, 8, 45), ncol=2), correct=F)


	Pearson's Chi-squared test

data:  matrix(c(43, 4, 8, 45), ncol = 2)
X-squared = 58.175, df = 1, p-value = 2.398e-14


## Problem 6
A researcher is studying migration patterns. She collected the location of the current and previous homes for subjects who moved across regions (Northeast, Souteast and West). She recorded the following:


x=c(267, 255, 139)

y = c(135, 240, 234)


In [67]:
x=c(267, 255, 139)
y = c(135, 240, 234)

chisq.test(x, p=y/sum(y), correct=FALSE)
t(round(chisq$expected,2))


	Chi-squared test for given probabilities

data:  x
X-squared = 151.22, df = 2, p-value < 2.2e-16


A    B   
none                70.0 70.0
nausea              22.5 22.5
nausea and vomiting  7.5  7.5

In [68]:
dtm = matrix(c(267, 255, 139, 135, 240, 234), ncol=2, byrow=F)
dtm
chisq.test(dtm, correct=FALSE)
t(round(chisq$expected,2))

[,1] [,2]
[1,] 267  135 
[2,] 255  240 
[3,] 139  234


	Pearson's Chi-squared test

data:  dtm
X-squared = 65.975, df = 2, p-value = 4.717e-15


A    B   
none                70.0 70.0
nausea              22.5 22.5
nausea and vomiting  7.5  7.5

## Problem 7
Standard decks of playing cards have 13 cards of each suit (diamonds, clubs, hearts, spades) for a total of 52 cards. Someone gives you a 52 card deck. You draw a card, record its suit, replace the card, shuffle the deck and repeat that process 200 times, obtaining the following table

(46, 54, 49, 51)

In [59]:
chisq.test(c(46, 54, 49, 51), p=rep(1/4, 4), correct=F)


	Chi-squared test for given probabilities

data:  c(46, 54, 49, 51)
X-squared = 0.68, df = 3, p-value = 0.8779


## Problem 3
In a review of the author Jane Austen's work, scholars found the following relative frequencies of the words an''an'', that'' and “this''

In [53]:
props=c(.53, .35, .12)
counts=c(140, 100, 50)
sum(props)

[1] 1

### Chi-square Test

In [25]:
chisq<-chisq.test(counts, p=props, correct=FALSE)
chisq

cat('\n*** Expected:\n')
t(round(chisq$expected,2))


	Chi-squared test for given probabilities

data:  counts
X-squared = 7.8824, df = 2, p-value = 0.01942



*** Expected:


[,1]  [,2]  [,3]
[1,] 153.7 101.5 34.8

## Problem 4
Two drugs, A and B , are being investigated in a randomized trial with the data are given below. Investigators would like to know if the Drug A and Drug B are equivalent in the terms of the distribution of side effects.

In [61]:
drg_a = c(80, 15, 5)
drg_b = c(60, 30, 10)
dtm = matrix(c(drg_a, drg_b), nrow=2, byrow=T)
colnames(dtm)<-c('none', 'nausea', 'nausea and vomiting')
rownames(dtm)<-c('A', 'B')
dtt = as.table(dtm)
dtt

cat('*** Margins 1:\n')
margin.table(dtt, 1)
cat('*** Margins 2:\n')
margin.table(dtt, 2)

  none nausea nausea and vomiting
A   80     15                   5
B   60     30                  10

*** Margins 1:


  A   B 
100 100 

*** Margins 2:


               none              nausea nausea and vomiting 
                140                  45                  15 

### Chi-square Test

In [62]:
chisq<-chisq.test(dtm, correct=FALSE)
chisq

cat('\n*** Expected:\n')
t(round(chisq$expected,2))

cat('*** Expected Margins 1:\n')
t(margin.table(chisq$expected, 1))

cat('*** Expected Margins 2:\n')
t(margin.table(chisq$expected, 2))


	Pearson's Chi-squared test

data:  dtm
X-squared = 9.5238, df = 2, p-value = 0.008549



*** Expected:


A    B   
none                70.0 70.0
nausea              22.5 22.5
nausea and vomiting  7.5  7.5

*** Expected Margins 1:


A   B  
[1,] 100 100

*** Expected Margins 2:


none nausea nausea and vomiting
[1,] 140  45     15

## Problem 5

In [595]:
props=c(.301, .176, .125, .097, .079, .067, .058, .051, .046)
# props=round(log10((1:9) + 1) - log10(1:9), 3)
counts=c(275, 183, 133, 111, 76, 66, 66, 44, 56)

### Chi-square Test

In [596]:
chisq<-chisq.test(counts, p=p, correct=FALSE)
chisq

cat('\n*** Expected:\n')
t(round(chisq$expected,2))

cat('*** Expected Margins 1:\n')
t(margin.table(chisq$expected, 1))

cat('*** Expected Margins 2:\n')
t(margin.table(chisq$expected, 2))


	Chi-squared test for given probabilities

data:  counts
X-squared = 9.4361, df = 8, p-value = 0.3069



*** Expected:


[,1]   [,2]   [,3]   [,4]  [,5]  [,6]  [,7]  [,8]  [,9] 
[1,] 304.04 177.85 126.19 97.88 79.97 67.62 58.57 51.66 46.22

*** Expected Margins 1:


ERROR: Error in margin.table(chisq$expected, 1): 'x' is not an array


## Problem 6

In [1]:
dtf = matrix(c(65, 35, 70, 30, 15, 85), ncol=2, byrow=T)
colnames(dtf) <- c('high', 'low')
rownames(dtf) <- c('Exec', 'Prof', 'Lion Tamer')

dtf = as.table(dtf)
dtf

margin.table(dtf, 1)
margin.table(dtf, 2)

           high low
Exec         65  35
Prof         70  30
Lion Tamer   15  85

      Exec       Prof Lion Tamer 
       100        100        100 

high  low 
 150  150 

### Chi-square Test

In [3]:
chisq<-chisq.test(dtf, correct=FALSE)
chisq

cat('\n*** Expected:\n')
t(round(chisq$expected,2))

cat('*** Expected Margins 1:\n')
t(margin.table(chisq$expected, 1))

cat('*** Expected Margins 2:\n')
t(margin.table(chisq$expected, 2))


	Pearson's Chi-squared test

data:  dtf
X-squared = 74, df = 2, p-value < 2.2e-16



*** Expected:


Exec Prof Lion Tamer
high 50   50   50        
low  50   50   50

*** Expected Margins 1:


Exec Prof Lion Tamer
[1,] 100  100  100

*** Expected Margins 2:


high low
[1,] 150  150